services:
  traefik:
    image: traefik:v3.6.1
    container_name: shreyws-traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=tcp://socket-proxy:2375"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.metrics.address=:8082"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entrypoint=metrics"

      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.fields.defaultmode=keep"
      - "--accesslog.fields.names.RequestPath=drop"
      - "--accesslog.fields.names.RequestAddr=drop"
      - "--accesslog.fields.names.ClientUsername=drop"
      - "--accesslog.fields.headers.defaultmode=drop"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /srv/shreyws/infra/compose/traefik/dynamic:/etc/traefik/dynamic:ro
      - /srv/shreyws/secrets/traefik/tls:/certs:ro

    healthcheck:
      test:
        - CMD
        - wget
        - -q
        - --spider
        - http://127.0.0.1:8082/metrics
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

    networks:
      - traefik_default
      - pilot_frontend
      - docker_socket_proxy
    labels:
      - diun.enable=true

networks:
  traefik_default:
    external: true
  pilot_frontend:
    external: true
  docker_socket_proxy:
    external: true
